name: Train & Deploy Qwen2 LoRA

# ----------------------------------------------------------------------
# Триггеры
# ----------------------------------------------------------------------
on:
  push:
    branches: [ main ]
  workflow_dispatch:          # позволяет запускать вручную

# ----------------------------------------------------------------------
# Описание jobs
# ----------------------------------------------------------------------
jobs:
  train:
    # --------------------------------------------------------------
    # 1️⃣ Если у вас есть self‑hosted GPU‑runner, раскомментируйте строку ниже
    # --------------------------------------------------------------
    # runs-on: [self-hosted, gpu]   # <-- runner с установленным NVIDIA‑GPU
    # --------------------------------------------------------------
    # 2️⃣ Если GPU‑раннера нет – используем обычный GitHub‑hosted runner
    # --------------------------------------------------------------
    runs-on: ubuntu-latest

    steps:
      # ------------------------------------------------------------------
      # Checkout
      # ------------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ------------------------------------------------------------------
      # Python
      # ------------------------------------------------------------------
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # ------------------------------------------------------------------
      # Install deps
      # ------------------------------------------------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ------------------------------------------------------------------
      # Run training (and optional push to HF Hub)
      # ------------------------------------------------------------------
      - name: Run training & push to HF Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}   # токен из Secrets
        run: |
          python train.py \
            --input_file data.txt \
            --output_dir ./my_finetuned \
            --model_name "Qwen/Qwen2-0.5B-Instruct" \
            --epochs 40 \
            --batch_size 2 \
            --gradient_accumulation 4 \
            --learning_rate 1e-5 \
            --max_length 256 \
            --repeat_factor 8 \
            --save_full_model \
            --generate \
            --prompt "Тогда мы постоим, а вечером уйдём домой строчить в интернет!" \
            --max_new_tokens 200 \
            --push_to_hub \
            --hf_username ${{ github.actor }} \
            --hf_repo_name qwen2-finetuned-${{ github.run_id }}